import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import '../constants/api_constants.dart';

class MNotifyService {
  static Future<bool> sendInvoiceSms({
    required String phoneNumber,
    required String clientName,
    required String invoiceNumber,
    required double totalAmount,
    required DateTime dueDate,
  }) async {
    // Clean the phone number (mNotify usually wants it without the +)
    String formattedPhone = phoneNumber.replaceAll('+', '').trim();

    final dateFormat = DateFormat('MMM dd, yyyy');
    final formattedDate = dateFormat.format(dueDate);

    final String message =
        'Hello $clientName, invoice $invoiceNumber for GHS ${totalAmount.toStringAsFixed(2)} has been generated by PEN Network. Payment is due by $formattedDate. Thank you.';

    final String url =
        'https://api.mnotify.com/api/sms/quick?key=${ApiConstants.mNotifyApiKey}';

    // FIX: Changed is_schedule to a proper boolean and removed the empty date string
    final Map<String, dynamic> payload = {
      'recipient': [formattedPhone],
      'sender': ApiConstants.senderId,
      'message': message,
      'is_schedule': false,
    };

    try {
      final response = await http.post(
        Uri.parse(url),
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: jsonEncode(payload),
      );

      if (response.statusCode == 200) {
        final responseData = jsonDecode(response.body);
        if (responseData['status'] == 'success') {
          return true;
        } else {
          print('mNotify Error Details: ${response.body}');
          return false;
        }
      } else {
        // FIX: Now we will actually see WHY mNotify rejected it!
        print('HTTP Error ${response.statusCode}: ${response.body}');
        return false;
      }
    } catch (e) {
      print('Exception sending SMS: $e');
      return false;
    }
  }
}
