// ignore_for_file: avoid_print

import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import '../constants/api_constants.dart';

class MNotifyService {
  // -----------------------------------------------------------------
  // 1. SEND INVOICE SMS
  // -----------------------------------------------------------------
  static Future<bool> sendInvoiceSms({
    required String phoneNumber,
    required String clientName,
    required String companyName, // <-- NEW
    required String invoiceNumber,
    required double totalAmount,
    required DateTime dueDate,
  }) async {
    // Clean the phone number (mNotify usually wants it without the +)
    String formattedPhone = phoneNumber.replaceAll('+', '').trim();

    final dateFormat = DateFormat('MMM dd, yyyy');
    final formattedDate = dateFormat.format(dueDate);

    // FIX: Using dynamic company name!
    final String message =
        'Hello $clientName, invoice $invoiceNumber for GHS ${totalAmount.toStringAsFixed(2)} has been generated by $companyName. Payment is due by $formattedDate. Thank you.';

    final String url =
        'https://api.mnotify.com/api/sms/quick?key=${ApiConstants.mNotifyApiKey}';

    final Map<String, dynamic> payload = {
      'recipient': [formattedPhone],
      'sender': ApiConstants.senderId,
      'message': message,
      'is_schedule': false,
    };

    try {
      final response = await http.post(
        Uri.parse(url),
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: jsonEncode(payload),
      );

      if (response.statusCode == 200) {
        final responseData = jsonDecode(response.body);
        if (responseData['status'] == 'success') {
          return true;
        } else {
          print('mNotify Error Details: ${response.body}');
          return false;
        }
      } else {
        print('HTTP Error ${response.statusCode}: ${response.body}');
        return false;
      }
    } catch (e) {
      print('Exception sending SMS: $e');
      return false;
    }
  }

  // -----------------------------------------------------------------
  // 2. SEND PAYMENT RECEIPT SMS
  // -----------------------------------------------------------------
  static Future<bool> sendReceiptSms({
    required String phoneNumber,
    required String clientName,
    required String companyName, // <-- NEW
    required String invoiceNumber,
    required double amountPaid,
    required double balanceDue,
  }) async {
    // Clean the phone number
    String formattedPhone = phoneNumber.replaceAll('+', '').trim();

    final currencyFormat = NumberFormat.currency(
      symbol: 'GHS ',
      decimalDigits: 2,
    );
    final formattedAmount = currencyFormat.format(amountPaid);
    final formattedBalance = currencyFormat.format(balanceDue);

    // Draft a smart message based on the remaining balance
    String message =
        'Hello $clientName,\n we have received your payment of $formattedAmount for invoice $invoiceNumber.';

    if (balanceDue > 0) {
      message += '\nYour remaining balance is $formattedBalance.';
    } else {
      message += '\nThis invoice is now fully paid.';
    }
    // FIX: Using dynamic company name!
    message += '\nThank you, \n$companyName.';

    final String url =
        'https://api.mnotify.com/api/sms/quick?key=${ApiConstants.mNotifyApiKey}';

    final Map<String, dynamic> payload = {
      'recipient': [formattedPhone],
      'sender': ApiConstants.senderId,
      'message': message,
      'is_schedule': false,
    };

    try {
      final response = await http.post(
        Uri.parse(url),
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: jsonEncode(payload),
      );

      if (response.statusCode == 200) {
        final responseData = jsonDecode(response.body);
        if (responseData['status'] == 'success') {
          return true;
        } else {
          print('mNotify Receipt Error Details: ${response.body}');
          return false;
        }
      } else {
        print('HTTP Error ${response.statusCode}: ${response.body}');
        return false;
      }
    } catch (e) {
      print('Exception sending Receipt SMS: $e');
      return false;
    }
  }
}
