// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHNNkVHbrA2rGMURMY53VSP27LxEoc9ag',
    appId: '1:1054817026092:android:f9a30acc6231e080679189',
    messagingSenderId: '1054817026092',
    projectId: 'nledger-d66b6',
    storageBucket: 'nledger-d66b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEQdty3rUn4fbX4Z3Z_T7qLPJj6HIOhjM',
    appId: '1:1054817026092:ios:6bd9fff084d67175679189',
    messagingSenderId: '1054817026092',
    projectId: 'nledger-d66b6',
    storageBucket: 'nledger-d66b6.firebasestorage.app',
    iosBundleId: 'com.example.nledger',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjT21EzWDQjRMR2KGdnvS9Qhn-AdqDk0o',
    appId: '1:1054817026092:web:beb941ca84f85b4d679189',
    messagingSenderId: '1054817026092',
    projectId: 'nledger-d66b6',
    authDomain: 'nledger-d66b6.firebaseapp.com',
    storageBucket: 'nledger-d66b6.firebasestorage.app',
  );

}